// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: canvaz.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Spotify.Canvazcache {

  /// <summary>Holder for reflection information generated from canvaz.proto</summary>
  public static partial class CanvazReflection {

    #region Descriptor
    /// <summary>File descriptor for canvaz.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CanvazReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxjYW52YXoucHJvdG8SF2NvbS5zcG90aWZ5LmNhbnZhemNhY2hlGhFjYW52",
            "YXotbWV0YS5wcm90byIzCgZBcnRpc3QSCwoDdXJpGAEgASgJEgwKBG5hbWUY",
            "AiABKAkSDgoGYXZhdGFyGAMgASgJIuECChRFbnRpdHlDYW52YXpSZXNwb25z",
            "ZRJGCghjYW52YXNlcxgBIAMoCzI0LmNvbS5zcG90aWZ5LmNhbnZhemNhY2hl",
            "LkVudGl0eUNhbnZhelJlc3BvbnNlLkNhbnZhehIWCg50dGxfaW5fc2Vjb25k",
            "cxgCIAEoAxroAQoGQ2FudmF6EgoKAmlkGAEgASgJEgsKA3VybBgCIAEoCRIP",
            "CgdmaWxlX2lkGAMgASgJEiYKBHR5cGUYBCABKA4yGC5jb20uc3BvdGlmeS5j",
            "YW52YXouVHlwZRISCgplbnRpdHlfdXJpGAUgASgJEi8KBmFydGlzdBgGIAEo",
            "CzIfLmNvbS5zcG90aWZ5LmNhbnZhemNhY2hlLkFydGlzdBIQCghleHBsaWNp",
            "dBgHIAEoCBITCgt1cGxvYWRlZF9ieRgIIAEoCRIMCgRldGFnGAkgASgJEhIK",
            "CmNhbnZhc191cmkYCyABKAkiiAEKE0VudGl0eUNhbnZhelJlcXVlc3QSRQoI",
            "ZW50aXRpZXMYASADKAsyMy5jb20uc3BvdGlmeS5jYW52YXpjYWNoZS5FbnRp",
            "dHlDYW52YXpSZXF1ZXN0LkVudGl0eRoqCgZFbnRpdHkSEgoKZW50aXR5X3Vy",
            "aRgBIAEoCRIMCgRldGFnGAIgASgJQhYKEmNvbS5zcG90aWZ5LmNhbnZhekgC",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Spotify.Canvaz.CanvazMetaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Spotify.Canvazcache.Artist), global::Com.Spotify.Canvazcache.Artist.Parser, new[]{ "Uri", "Name", "Avatar" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Spotify.Canvazcache.EntityCanvazResponse), global::Com.Spotify.Canvazcache.EntityCanvazResponse.Parser, new[]{ "Canvases", "TtlInSeconds" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz), global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz.Parser, new[]{ "Id", "Url", "FileId", "Type", "EntityUri", "Artist", "Explicit", "UploadedBy", "Etag", "CanvasUri" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Spotify.Canvazcache.EntityCanvazRequest), global::Com.Spotify.Canvazcache.EntityCanvazRequest.Parser, new[]{ "Entities" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity), global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity.Parser, new[]{ "EntityUri", "Etag" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Artist : pb::IMessage<Artist>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Artist> _parser = new pb::MessageParser<Artist>(() => new Artist());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Artist> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Spotify.Canvazcache.CanvazReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Artist() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Artist(Artist other) : this() {
      uri_ = other.uri_;
      name_ = other.name_;
      avatar_ = other.avatar_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Artist Clone() {
      return new Artist(this);
    }

    /// <summary>Field number for the "uri" field.</summary>
    public const int UriFieldNumber = 1;
    private string uri_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uri {
      get { return uri_; }
      set {
        uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 3;
    private string avatar_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Avatar {
      get { return avatar_; }
      set {
        avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Artist);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Artist other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uri != other.Uri) return false;
      if (Name != other.Name) return false;
      if (Avatar != other.Avatar) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uri.Length != 0) hash ^= Uri.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uri.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uri);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Avatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uri.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uri);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Avatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Avatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Artist other) {
      if (other == null) {
        return;
      }
      if (other.Uri.Length != 0) {
        Uri = other.Uri;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Avatar.Length != 0) {
        Avatar = other.Avatar;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uri = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Avatar = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uri = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Avatar = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityCanvazResponse : pb::IMessage<EntityCanvazResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityCanvazResponse> _parser = new pb::MessageParser<EntityCanvazResponse>(() => new EntityCanvazResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityCanvazResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Spotify.Canvazcache.CanvazReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazResponse(EntityCanvazResponse other) : this() {
      canvases_ = other.canvases_.Clone();
      ttlInSeconds_ = other.ttlInSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazResponse Clone() {
      return new EntityCanvazResponse(this);
    }

    /// <summary>Field number for the "canvases" field.</summary>
    public const int CanvasesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz> _repeated_canvases_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz.Parser);
    private readonly pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz> canvases_ = new pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazResponse.Types.Canvaz> Canvases {
      get { return canvases_; }
    }

    /// <summary>Field number for the "ttl_in_seconds" field.</summary>
    public const int TtlInSecondsFieldNumber = 2;
    private long ttlInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TtlInSeconds {
      get { return ttlInSeconds_; }
      set {
        ttlInSeconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityCanvazResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityCanvazResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!canvases_.Equals(other.canvases_)) return false;
      if (TtlInSeconds != other.TtlInSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= canvases_.GetHashCode();
      if (TtlInSeconds != 0L) hash ^= TtlInSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      canvases_.WriteTo(output, _repeated_canvases_codec);
      if (TtlInSeconds != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      canvases_.WriteTo(ref output, _repeated_canvases_codec);
      if (TtlInSeconds != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += canvases_.CalculateSize(_repeated_canvases_codec);
      if (TtlInSeconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TtlInSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityCanvazResponse other) {
      if (other == null) {
        return;
      }
      canvases_.Add(other.canvases_);
      if (other.TtlInSeconds != 0L) {
        TtlInSeconds = other.TtlInSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            canvases_.AddEntriesFrom(input, _repeated_canvases_codec);
            break;
          }
          case 16: {
            TtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            canvases_.AddEntriesFrom(ref input, _repeated_canvases_codec);
            break;
          }
          case 16: {
            TtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EntityCanvazResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Canvaz : pb::IMessage<Canvaz>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Canvaz> _parser = new pb::MessageParser<Canvaz>(() => new Canvaz());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Canvaz> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Spotify.Canvazcache.EntityCanvazResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Canvaz() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Canvaz(Canvaz other) : this() {
          id_ = other.id_;
          url_ = other.url_;
          fileId_ = other.fileId_;
          type_ = other.type_;
          entityUri_ = other.entityUri_;
          artist_ = other.artist_ != null ? other.artist_.Clone() : null;
          explicit_ = other.explicit_;
          uploadedBy_ = other.uploadedBy_;
          etag_ = other.etag_;
          canvasUri_ = other.canvasUri_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Canvaz Clone() {
          return new Canvaz(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id {
          get { return id_; }
          set {
            id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "url" field.</summary>
        public const int UrlFieldNumber = 2;
        private string url_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Url {
          get { return url_; }
          set {
            url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "file_id" field.</summary>
        public const int FileIdFieldNumber = 3;
        private string fileId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string FileId {
          get { return fileId_; }
          set {
            fileId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 4;
        private global::Com.Spotify.Canvaz.Type type_ = global::Com.Spotify.Canvaz.Type.Image;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Com.Spotify.Canvaz.Type Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "entity_uri" field.</summary>
        public const int EntityUriFieldNumber = 5;
        private string entityUri_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string EntityUri {
          get { return entityUri_; }
          set {
            entityUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "artist" field.</summary>
        public const int ArtistFieldNumber = 6;
        private global::Com.Spotify.Canvazcache.Artist artist_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Com.Spotify.Canvazcache.Artist Artist {
          get { return artist_; }
          set {
            artist_ = value;
          }
        }

        /// <summary>Field number for the "explicit" field.</summary>
        public const int ExplicitFieldNumber = 7;
        private bool explicit_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Explicit {
          get { return explicit_; }
          set {
            explicit_ = value;
          }
        }

        /// <summary>Field number for the "uploaded_by" field.</summary>
        public const int UploadedByFieldNumber = 8;
        private string uploadedBy_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string UploadedBy {
          get { return uploadedBy_; }
          set {
            uploadedBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "etag" field.</summary>
        public const int EtagFieldNumber = 9;
        private string etag_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Etag {
          get { return etag_; }
          set {
            etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "canvas_uri" field.</summary>
        public const int CanvasUriFieldNumber = 11;
        private string canvasUri_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string CanvasUri {
          get { return canvasUri_; }
          set {
            canvasUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Canvaz);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Canvaz other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (Url != other.Url) return false;
          if (FileId != other.FileId) return false;
          if (Type != other.Type) return false;
          if (EntityUri != other.EntityUri) return false;
          if (!object.Equals(Artist, other.Artist)) return false;
          if (Explicit != other.Explicit) return false;
          if (UploadedBy != other.UploadedBy) return false;
          if (Etag != other.Etag) return false;
          if (CanvasUri != other.CanvasUri) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Id.Length != 0) hash ^= Id.GetHashCode();
          if (Url.Length != 0) hash ^= Url.GetHashCode();
          if (FileId.Length != 0) hash ^= FileId.GetHashCode();
          if (Type != global::Com.Spotify.Canvaz.Type.Image) hash ^= Type.GetHashCode();
          if (EntityUri.Length != 0) hash ^= EntityUri.GetHashCode();
          if (artist_ != null) hash ^= Artist.GetHashCode();
          if (Explicit != false) hash ^= Explicit.GetHashCode();
          if (UploadedBy.Length != 0) hash ^= UploadedBy.GetHashCode();
          if (Etag.Length != 0) hash ^= Etag.GetHashCode();
          if (CanvasUri.Length != 0) hash ^= CanvasUri.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Id.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Id);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Url);
          }
          if (FileId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(FileId);
          }
          if (Type != global::Com.Spotify.Canvaz.Type.Image) {
            output.WriteRawTag(32);
            output.WriteEnum((int) Type);
          }
          if (EntityUri.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(EntityUri);
          }
          if (artist_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(Artist);
          }
          if (Explicit != false) {
            output.WriteRawTag(56);
            output.WriteBool(Explicit);
          }
          if (UploadedBy.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(UploadedBy);
          }
          if (Etag.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(Etag);
          }
          if (CanvasUri.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(CanvasUri);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Id.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Id);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Url);
          }
          if (FileId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(FileId);
          }
          if (Type != global::Com.Spotify.Canvaz.Type.Image) {
            output.WriteRawTag(32);
            output.WriteEnum((int) Type);
          }
          if (EntityUri.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(EntityUri);
          }
          if (artist_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(Artist);
          }
          if (Explicit != false) {
            output.WriteRawTag(56);
            output.WriteBool(Explicit);
          }
          if (UploadedBy.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(UploadedBy);
          }
          if (Etag.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(Etag);
          }
          if (CanvasUri.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(CanvasUri);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Id.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
          }
          if (Url.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
          }
          if (FileId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(FileId);
          }
          if (Type != global::Com.Spotify.Canvaz.Type.Image) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (EntityUri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUri);
          }
          if (artist_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Artist);
          }
          if (Explicit != false) {
            size += 1 + 1;
          }
          if (UploadedBy.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(UploadedBy);
          }
          if (Etag.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
          }
          if (CanvasUri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CanvasUri);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Canvaz other) {
          if (other == null) {
            return;
          }
          if (other.Id.Length != 0) {
            Id = other.Id;
          }
          if (other.Url.Length != 0) {
            Url = other.Url;
          }
          if (other.FileId.Length != 0) {
            FileId = other.FileId;
          }
          if (other.Type != global::Com.Spotify.Canvaz.Type.Image) {
            Type = other.Type;
          }
          if (other.EntityUri.Length != 0) {
            EntityUri = other.EntityUri;
          }
          if (other.artist_ != null) {
            if (artist_ == null) {
              Artist = new global::Com.Spotify.Canvazcache.Artist();
            }
            Artist.MergeFrom(other.Artist);
          }
          if (other.Explicit != false) {
            Explicit = other.Explicit;
          }
          if (other.UploadedBy.Length != 0) {
            UploadedBy = other.UploadedBy;
          }
          if (other.Etag.Length != 0) {
            Etag = other.Etag;
          }
          if (other.CanvasUri.Length != 0) {
            CanvasUri = other.CanvasUri;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Id = input.ReadString();
                break;
              }
              case 18: {
                Url = input.ReadString();
                break;
              }
              case 26: {
                FileId = input.ReadString();
                break;
              }
              case 32: {
                Type = (global::Com.Spotify.Canvaz.Type) input.ReadEnum();
                break;
              }
              case 42: {
                EntityUri = input.ReadString();
                break;
              }
              case 50: {
                if (artist_ == null) {
                  Artist = new global::Com.Spotify.Canvazcache.Artist();
                }
                input.ReadMessage(Artist);
                break;
              }
              case 56: {
                Explicit = input.ReadBool();
                break;
              }
              case 66: {
                UploadedBy = input.ReadString();
                break;
              }
              case 74: {
                Etag = input.ReadString();
                break;
              }
              case 90: {
                CanvasUri = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Id = input.ReadString();
                break;
              }
              case 18: {
                Url = input.ReadString();
                break;
              }
              case 26: {
                FileId = input.ReadString();
                break;
              }
              case 32: {
                Type = (global::Com.Spotify.Canvaz.Type) input.ReadEnum();
                break;
              }
              case 42: {
                EntityUri = input.ReadString();
                break;
              }
              case 50: {
                if (artist_ == null) {
                  Artist = new global::Com.Spotify.Canvazcache.Artist();
                }
                input.ReadMessage(Artist);
                break;
              }
              case 56: {
                Explicit = input.ReadBool();
                break;
              }
              case 66: {
                UploadedBy = input.ReadString();
                break;
              }
              case 74: {
                Etag = input.ReadString();
                break;
              }
              case 90: {
                CanvasUri = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class EntityCanvazRequest : pb::IMessage<EntityCanvazRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityCanvazRequest> _parser = new pb::MessageParser<EntityCanvazRequest>(() => new EntityCanvazRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityCanvazRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Spotify.Canvazcache.CanvazReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazRequest(EntityCanvazRequest other) : this() {
      entities_ = other.entities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityCanvazRequest Clone() {
      return new EntityCanvazRequest(this);
    }

    /// <summary>Field number for the "entities" field.</summary>
    public const int EntitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity> _repeated_entities_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity.Parser);
    private readonly pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity> entities_ = new pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Spotify.Canvazcache.EntityCanvazRequest.Types.Entity> Entities {
      get { return entities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityCanvazRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityCanvazRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entities_.Equals(other.entities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entities_.WriteTo(output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entities_.WriteTo(ref output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += entities_.CalculateSize(_repeated_entities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityCanvazRequest other) {
      if (other == null) {
        return;
      }
      entities_.Add(other.entities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entities_.AddEntriesFrom(input, _repeated_entities_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entities_.AddEntriesFrom(ref input, _repeated_entities_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EntityCanvazRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Entity : pb::IMessage<Entity>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Entity> _parser = new pb::MessageParser<Entity>(() => new Entity());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Entity> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Spotify.Canvazcache.EntityCanvazRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity(Entity other) : this() {
          entityUri_ = other.entityUri_;
          etag_ = other.etag_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity Clone() {
          return new Entity(this);
        }

        /// <summary>Field number for the "entity_uri" field.</summary>
        public const int EntityUriFieldNumber = 1;
        private string entityUri_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string EntityUri {
          get { return entityUri_; }
          set {
            entityUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "etag" field.</summary>
        public const int EtagFieldNumber = 2;
        private string etag_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Etag {
          get { return etag_; }
          set {
            etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Entity);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Entity other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (EntityUri != other.EntityUri) return false;
          if (Etag != other.Etag) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (EntityUri.Length != 0) hash ^= EntityUri.GetHashCode();
          if (Etag.Length != 0) hash ^= Etag.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (EntityUri.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(EntityUri);
          }
          if (Etag.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Etag);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (EntityUri.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(EntityUri);
          }
          if (Etag.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Etag);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (EntityUri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUri);
          }
          if (Etag.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Entity other) {
          if (other == null) {
            return;
          }
          if (other.EntityUri.Length != 0) {
            EntityUri = other.EntityUri;
          }
          if (other.Etag.Length != 0) {
            Etag = other.Etag;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                EntityUri = input.ReadString();
                break;
              }
              case 18: {
                Etag = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                EntityUri = input.ReadString();
                break;
              }
              case 18: {
                Etag = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
