// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: canvaz-meta.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Spotify.Canvaz {

  /// <summary>Holder for reflection information generated from canvaz-meta.proto</summary>
  public static partial class CanvazMetaReflection {

    #region Descriptor
    /// <summary>File descriptor for canvaz-meta.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CanvazMetaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjYW52YXotbWV0YS5wcm90bxISY29tLnNwb3RpZnkuY2FudmF6KlIKBFR5",
            "cGUSCQoFSU1BR0UQABIJCgVWSURFTxABEhEKDVZJREVPX0xPT1BJTkcQAhIY",
            "ChRWSURFT19MT09QSU5HX1JBTkRPTRADEgcKA0dJRhAEQhYKEmNvbS5zcG90",
            "aWZ5LmNhbnZhekgCYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Spotify.Canvaz.Type), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Type {
    [pbr::OriginalName("IMAGE")] Image = 0,
    [pbr::OriginalName("VIDEO")] Video = 1,
    [pbr::OriginalName("VIDEO_LOOPING")] VideoLooping = 2,
    [pbr::OriginalName("VIDEO_LOOPING_RANDOM")] VideoLoopingRandom = 3,
    [pbr::OriginalName("GIF")] Gif = 4,
  }

  #endregion

}

#endregion Designer generated code
