// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: context_page.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spotify.Player.Proto {

  /// <summary>Holder for reflection information generated from context_page.proto</summary>
  public static partial class ContextPageReflection {

    #region Descriptor
    /// <summary>File descriptor for context_page.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContextPageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJjb250ZXh0X3BhZ2UucHJvdG8SFHNwb3RpZnkucGxheWVyLnByb3RvGhNj",
            "b250ZXh0X3RyYWNrLnByb3RvIu8BCgtDb250ZXh0UGFnZRIQCghwYWdlX3Vy",
            "bBgBIAEoCRIVCg1uZXh0X3BhZ2VfdXJsGAIgASgJEkEKCG1ldGFkYXRhGAMg",
            "AygLMi8uc3BvdGlmeS5wbGF5ZXIucHJvdG8uQ29udGV4dFBhZ2UuTWV0YWRh",
            "dGFFbnRyeRIyCgZ0cmFja3MYBCADKAsyIi5zcG90aWZ5LnBsYXllci5wcm90",
            "by5Db250ZXh0VHJhY2sSDwoHbG9hZGluZxgFIAEoCBovCg1NZXRhZGF0YUVu",
            "dHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCFwoTY29tLnNw",
            "b3RpZnkuY29udGV4dEgC"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Spotify.Player.Proto.ContextTrackReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Player.Proto.ContextPage), global::Spotify.Player.Proto.ContextPage.Parser, new[]{ "PageUrl", "NextPageUrl", "Metadata", "Tracks", "Loading" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ContextPage : pb::IMessage<ContextPage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ContextPage> _parser = new pb::MessageParser<ContextPage>(() => new ContextPage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContextPage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Player.Proto.ContextPageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContextPage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContextPage(ContextPage other) : this() {
      _hasBits0 = other._hasBits0;
      pageUrl_ = other.pageUrl_;
      nextPageUrl_ = other.nextPageUrl_;
      metadata_ = other.metadata_.Clone();
      tracks_ = other.tracks_.Clone();
      loading_ = other.loading_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContextPage Clone() {
      return new ContextPage(this);
    }

    /// <summary>Field number for the "page_url" field.</summary>
    public const int PageUrlFieldNumber = 1;
    private readonly static string PageUrlDefaultValue = "";

    private string pageUrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PageUrl {
      get { return pageUrl_ ?? PageUrlDefaultValue; }
      set {
        pageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "page_url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPageUrl {
      get { return pageUrl_ != null; }
    }
    /// <summary>Clears the value of the "page_url" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPageUrl() {
      pageUrl_ = null;
    }

    /// <summary>Field number for the "next_page_url" field.</summary>
    public const int NextPageUrlFieldNumber = 2;
    private readonly static string NextPageUrlDefaultValue = "";

    private string nextPageUrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NextPageUrl {
      get { return nextPageUrl_ ?? NextPageUrlDefaultValue; }
      set {
        nextPageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "next_page_url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasNextPageUrl {
      get { return nextPageUrl_ != null; }
    }
    /// <summary>Clears the value of the "next_page_url" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearNextPageUrl() {
      nextPageUrl_ = null;
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 3;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 26);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    /// <summary>Field number for the "tracks" field.</summary>
    public const int TracksFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Spotify.Player.Proto.ContextTrack> _repeated_tracks_codec
        = pb::FieldCodec.ForMessage(34, global::Spotify.Player.Proto.ContextTrack.Parser);
    private readonly pbc::RepeatedField<global::Spotify.Player.Proto.ContextTrack> tracks_ = new pbc::RepeatedField<global::Spotify.Player.Proto.ContextTrack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Spotify.Player.Proto.ContextTrack> Tracks {
      get { return tracks_; }
    }

    /// <summary>Field number for the "loading" field.</summary>
    public const int LoadingFieldNumber = 5;
    private readonly static bool LoadingDefaultValue = false;

    private bool loading_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Loading {
      get { if ((_hasBits0 & 1) != 0) { return loading_; } else { return LoadingDefaultValue; } }
      set {
        _hasBits0 |= 1;
        loading_ = value;
      }
    }
    /// <summary>Gets whether the "loading" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasLoading {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "loading" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearLoading() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContextPage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContextPage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PageUrl != other.PageUrl) return false;
      if (NextPageUrl != other.NextPageUrl) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      if(!tracks_.Equals(other.tracks_)) return false;
      if (Loading != other.Loading) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPageUrl) hash ^= PageUrl.GetHashCode();
      if (HasNextPageUrl) hash ^= NextPageUrl.GetHashCode();
      hash ^= Metadata.GetHashCode();
      hash ^= tracks_.GetHashCode();
      if (HasLoading) hash ^= Loading.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPageUrl) {
        output.WriteRawTag(10);
        output.WriteString(PageUrl);
      }
      if (HasNextPageUrl) {
        output.WriteRawTag(18);
        output.WriteString(NextPageUrl);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      tracks_.WriteTo(output, _repeated_tracks_codec);
      if (HasLoading) {
        output.WriteRawTag(40);
        output.WriteBool(Loading);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPageUrl) {
        output.WriteRawTag(10);
        output.WriteString(PageUrl);
      }
      if (HasNextPageUrl) {
        output.WriteRawTag(18);
        output.WriteString(NextPageUrl);
      }
      metadata_.WriteTo(ref output, _map_metadata_codec);
      tracks_.WriteTo(ref output, _repeated_tracks_codec);
      if (HasLoading) {
        output.WriteRawTag(40);
        output.WriteBool(Loading);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasPageUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PageUrl);
      }
      if (HasNextPageUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NextPageUrl);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      size += tracks_.CalculateSize(_repeated_tracks_codec);
      if (HasLoading) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContextPage other) {
      if (other == null) {
        return;
      }
      if (other.HasPageUrl) {
        PageUrl = other.PageUrl;
      }
      if (other.HasNextPageUrl) {
        NextPageUrl = other.NextPageUrl;
      }
      metadata_.Add(other.metadata_);
      tracks_.Add(other.tracks_);
      if (other.HasLoading) {
        Loading = other.Loading;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PageUrl = input.ReadString();
            break;
          }
          case 18: {
            NextPageUrl = input.ReadString();
            break;
          }
          case 26: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 34: {
            tracks_.AddEntriesFrom(input, _repeated_tracks_codec);
            break;
          }
          case 40: {
            Loading = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PageUrl = input.ReadString();
            break;
          }
          case 18: {
            NextPageUrl = input.ReadString();
            break;
          }
          case 26: {
            metadata_.AddEntriesFrom(ref input, _map_metadata_codec);
            break;
          }
          case 34: {
            tracks_.AddEntriesFrom(ref input, _repeated_tracks_codec);
            break;
          }
          case 40: {
            Loading = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
