// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: restrictions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spotify.Player.Proto {

  /// <summary>Holder for reflection information generated from restrictions.proto</summary>
  public static partial class RestrictionsReflection {

    #region Descriptor
    /// <summary>File descriptor for restrictions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RestrictionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJyZXN0cmljdGlvbnMucHJvdG8SFHNwb3RpZnkucGxheWVyLnByb3RvIrsH",
            "CgxSZXN0cmljdGlvbnMSIAoYZGlzYWxsb3dfcGF1c2luZ19yZWFzb25zGAEg",
            "AygJEiEKGWRpc2FsbG93X3Jlc3VtaW5nX3JlYXNvbnMYAiADKAkSIAoYZGlz",
            "YWxsb3dfc2Vla2luZ19yZWFzb25zGAMgAygJEiUKHWRpc2FsbG93X3BlZWtp",
            "bmdfcHJldl9yZWFzb25zGAQgAygJEiUKHWRpc2FsbG93X3BlZWtpbmdfbmV4",
            "dF9yZWFzb25zGAUgAygJEiYKHmRpc2FsbG93X3NraXBwaW5nX3ByZXZfcmVh",
            "c29ucxgGIAMoCRImCh5kaXNhbGxvd19za2lwcGluZ19uZXh0X3JlYXNvbnMY",
            "ByADKAkSMAooZGlzYWxsb3dfdG9nZ2xpbmdfcmVwZWF0X2NvbnRleHRfcmVh",
            "c29ucxgIIAMoCRIuCiZkaXNhbGxvd190b2dnbGluZ19yZXBlYXRfdHJhY2tf",
            "cmVhc29ucxgJIAMoCRIpCiFkaXNhbGxvd190b2dnbGluZ19zaHVmZmxlX3Jl",
            "YXNvbnMYCiADKAkSIgoaZGlzYWxsb3dfc2V0X3F1ZXVlX3JlYXNvbnMYCyAD",
            "KAkSLgomZGlzYWxsb3dfaW50ZXJydXB0aW5nX3BsYXliYWNrX3JlYXNvbnMY",
            "DCADKAkSLgomZGlzYWxsb3dfdHJhbnNmZXJyaW5nX3BsYXliYWNrX3JlYXNv",
            "bnMYDSADKAkSJwofZGlzYWxsb3dfcmVtb3RlX2NvbnRyb2xfcmVhc29ucxgO",
            "IAMoCRIzCitkaXNhbGxvd19pbnNlcnRpbmdfaW50b19uZXh0X3RyYWNrc19y",
            "ZWFzb25zGA8gAygJEjYKLmRpc2FsbG93X2luc2VydGluZ19pbnRvX2NvbnRl",
            "eHRfdHJhY2tzX3JlYXNvbnMYECADKAkSMgoqZGlzYWxsb3dfcmVvcmRlcmlu",
            "Z19pbl9uZXh0X3RyYWNrc19yZWFzb25zGBEgAygJEjUKLWRpc2FsbG93X3Jl",
            "b3JkZXJpbmdfaW5fY29udGV4dF90cmFja3NfcmVhc29ucxgSIAMoCRIyCipk",
            "aXNhbGxvd19yZW1vdmluZ19mcm9tX25leHRfdHJhY2tzX3JlYXNvbnMYEyAD",
            "KAkSNQotZGlzYWxsb3dfcmVtb3ZpbmdfZnJvbV9jb250ZXh0X3RyYWNrc19y",
            "ZWFzb25zGBQgAygJEikKIWRpc2FsbG93X3VwZGF0aW5nX2NvbnRleHRfcmVh",
            "c29ucxgVIAMoCUIXChNjb20uc3BvdGlmeS5jb250ZXh0SAI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Player.Proto.Restrictions), global::Spotify.Player.Proto.Restrictions.Parser, new[]{ "DisallowPausingReasons", "DisallowResumingReasons", "DisallowSeekingReasons", "DisallowPeekingPrevReasons", "DisallowPeekingNextReasons", "DisallowSkippingPrevReasons", "DisallowSkippingNextReasons", "DisallowTogglingRepeatContextReasons", "DisallowTogglingRepeatTrackReasons", "DisallowTogglingShuffleReasons", "DisallowSetQueueReasons", "DisallowInterruptingPlaybackReasons", "DisallowTransferringPlaybackReasons", "DisallowRemoteControlReasons", "DisallowInsertingIntoNextTracksReasons", "DisallowInsertingIntoContextTracksReasons", "DisallowReorderingInNextTracksReasons", "DisallowReorderingInContextTracksReasons", "DisallowRemovingFromNextTracksReasons", "DisallowRemovingFromContextTracksReasons", "DisallowUpdatingContextReasons" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Restrictions : pb::IMessage<Restrictions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Restrictions> _parser = new pb::MessageParser<Restrictions>(() => new Restrictions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Restrictions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Player.Proto.RestrictionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Restrictions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Restrictions(Restrictions other) : this() {
      disallowPausingReasons_ = other.disallowPausingReasons_.Clone();
      disallowResumingReasons_ = other.disallowResumingReasons_.Clone();
      disallowSeekingReasons_ = other.disallowSeekingReasons_.Clone();
      disallowPeekingPrevReasons_ = other.disallowPeekingPrevReasons_.Clone();
      disallowPeekingNextReasons_ = other.disallowPeekingNextReasons_.Clone();
      disallowSkippingPrevReasons_ = other.disallowSkippingPrevReasons_.Clone();
      disallowSkippingNextReasons_ = other.disallowSkippingNextReasons_.Clone();
      disallowTogglingRepeatContextReasons_ = other.disallowTogglingRepeatContextReasons_.Clone();
      disallowTogglingRepeatTrackReasons_ = other.disallowTogglingRepeatTrackReasons_.Clone();
      disallowTogglingShuffleReasons_ = other.disallowTogglingShuffleReasons_.Clone();
      disallowSetQueueReasons_ = other.disallowSetQueueReasons_.Clone();
      disallowInterruptingPlaybackReasons_ = other.disallowInterruptingPlaybackReasons_.Clone();
      disallowTransferringPlaybackReasons_ = other.disallowTransferringPlaybackReasons_.Clone();
      disallowRemoteControlReasons_ = other.disallowRemoteControlReasons_.Clone();
      disallowInsertingIntoNextTracksReasons_ = other.disallowInsertingIntoNextTracksReasons_.Clone();
      disallowInsertingIntoContextTracksReasons_ = other.disallowInsertingIntoContextTracksReasons_.Clone();
      disallowReorderingInNextTracksReasons_ = other.disallowReorderingInNextTracksReasons_.Clone();
      disallowReorderingInContextTracksReasons_ = other.disallowReorderingInContextTracksReasons_.Clone();
      disallowRemovingFromNextTracksReasons_ = other.disallowRemovingFromNextTracksReasons_.Clone();
      disallowRemovingFromContextTracksReasons_ = other.disallowRemovingFromContextTracksReasons_.Clone();
      disallowUpdatingContextReasons_ = other.disallowUpdatingContextReasons_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Restrictions Clone() {
      return new Restrictions(this);
    }

    /// <summary>Field number for the "disallow_pausing_reasons" field.</summary>
    public const int DisallowPausingReasonsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_disallowPausingReasons_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> disallowPausingReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowPausingReasons {
      get { return disallowPausingReasons_; }
    }

    /// <summary>Field number for the "disallow_resuming_reasons" field.</summary>
    public const int DisallowResumingReasonsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_disallowResumingReasons_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> disallowResumingReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowResumingReasons {
      get { return disallowResumingReasons_; }
    }

    /// <summary>Field number for the "disallow_seeking_reasons" field.</summary>
    public const int DisallowSeekingReasonsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_disallowSeekingReasons_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> disallowSeekingReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowSeekingReasons {
      get { return disallowSeekingReasons_; }
    }

    /// <summary>Field number for the "disallow_peeking_prev_reasons" field.</summary>
    public const int DisallowPeekingPrevReasonsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_disallowPeekingPrevReasons_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> disallowPeekingPrevReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowPeekingPrevReasons {
      get { return disallowPeekingPrevReasons_; }
    }

    /// <summary>Field number for the "disallow_peeking_next_reasons" field.</summary>
    public const int DisallowPeekingNextReasonsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_disallowPeekingNextReasons_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> disallowPeekingNextReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowPeekingNextReasons {
      get { return disallowPeekingNextReasons_; }
    }

    /// <summary>Field number for the "disallow_skipping_prev_reasons" field.</summary>
    public const int DisallowSkippingPrevReasonsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_disallowSkippingPrevReasons_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> disallowSkippingPrevReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowSkippingPrevReasons {
      get { return disallowSkippingPrevReasons_; }
    }

    /// <summary>Field number for the "disallow_skipping_next_reasons" field.</summary>
    public const int DisallowSkippingNextReasonsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_disallowSkippingNextReasons_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> disallowSkippingNextReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowSkippingNextReasons {
      get { return disallowSkippingNextReasons_; }
    }

    /// <summary>Field number for the "disallow_toggling_repeat_context_reasons" field.</summary>
    public const int DisallowTogglingRepeatContextReasonsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_disallowTogglingRepeatContextReasons_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> disallowTogglingRepeatContextReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowTogglingRepeatContextReasons {
      get { return disallowTogglingRepeatContextReasons_; }
    }

    /// <summary>Field number for the "disallow_toggling_repeat_track_reasons" field.</summary>
    public const int DisallowTogglingRepeatTrackReasonsFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_disallowTogglingRepeatTrackReasons_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> disallowTogglingRepeatTrackReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowTogglingRepeatTrackReasons {
      get { return disallowTogglingRepeatTrackReasons_; }
    }

    /// <summary>Field number for the "disallow_toggling_shuffle_reasons" field.</summary>
    public const int DisallowTogglingShuffleReasonsFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_disallowTogglingShuffleReasons_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> disallowTogglingShuffleReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowTogglingShuffleReasons {
      get { return disallowTogglingShuffleReasons_; }
    }

    /// <summary>Field number for the "disallow_set_queue_reasons" field.</summary>
    public const int DisallowSetQueueReasonsFieldNumber = 11;
    private static readonly pb::FieldCodec<string> _repeated_disallowSetQueueReasons_codec
        = pb::FieldCodec.ForString(90);
    private readonly pbc::RepeatedField<string> disallowSetQueueReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowSetQueueReasons {
      get { return disallowSetQueueReasons_; }
    }

    /// <summary>Field number for the "disallow_interrupting_playback_reasons" field.</summary>
    public const int DisallowInterruptingPlaybackReasonsFieldNumber = 12;
    private static readonly pb::FieldCodec<string> _repeated_disallowInterruptingPlaybackReasons_codec
        = pb::FieldCodec.ForString(98);
    private readonly pbc::RepeatedField<string> disallowInterruptingPlaybackReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowInterruptingPlaybackReasons {
      get { return disallowInterruptingPlaybackReasons_; }
    }

    /// <summary>Field number for the "disallow_transferring_playback_reasons" field.</summary>
    public const int DisallowTransferringPlaybackReasonsFieldNumber = 13;
    private static readonly pb::FieldCodec<string> _repeated_disallowTransferringPlaybackReasons_codec
        = pb::FieldCodec.ForString(106);
    private readonly pbc::RepeatedField<string> disallowTransferringPlaybackReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowTransferringPlaybackReasons {
      get { return disallowTransferringPlaybackReasons_; }
    }

    /// <summary>Field number for the "disallow_remote_control_reasons" field.</summary>
    public const int DisallowRemoteControlReasonsFieldNumber = 14;
    private static readonly pb::FieldCodec<string> _repeated_disallowRemoteControlReasons_codec
        = pb::FieldCodec.ForString(114);
    private readonly pbc::RepeatedField<string> disallowRemoteControlReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowRemoteControlReasons {
      get { return disallowRemoteControlReasons_; }
    }

    /// <summary>Field number for the "disallow_inserting_into_next_tracks_reasons" field.</summary>
    public const int DisallowInsertingIntoNextTracksReasonsFieldNumber = 15;
    private static readonly pb::FieldCodec<string> _repeated_disallowInsertingIntoNextTracksReasons_codec
        = pb::FieldCodec.ForString(122);
    private readonly pbc::RepeatedField<string> disallowInsertingIntoNextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowInsertingIntoNextTracksReasons {
      get { return disallowInsertingIntoNextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_inserting_into_context_tracks_reasons" field.</summary>
    public const int DisallowInsertingIntoContextTracksReasonsFieldNumber = 16;
    private static readonly pb::FieldCodec<string> _repeated_disallowInsertingIntoContextTracksReasons_codec
        = pb::FieldCodec.ForString(130);
    private readonly pbc::RepeatedField<string> disallowInsertingIntoContextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowInsertingIntoContextTracksReasons {
      get { return disallowInsertingIntoContextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_reordering_in_next_tracks_reasons" field.</summary>
    public const int DisallowReorderingInNextTracksReasonsFieldNumber = 17;
    private static readonly pb::FieldCodec<string> _repeated_disallowReorderingInNextTracksReasons_codec
        = pb::FieldCodec.ForString(138);
    private readonly pbc::RepeatedField<string> disallowReorderingInNextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowReorderingInNextTracksReasons {
      get { return disallowReorderingInNextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_reordering_in_context_tracks_reasons" field.</summary>
    public const int DisallowReorderingInContextTracksReasonsFieldNumber = 18;
    private static readonly pb::FieldCodec<string> _repeated_disallowReorderingInContextTracksReasons_codec
        = pb::FieldCodec.ForString(146);
    private readonly pbc::RepeatedField<string> disallowReorderingInContextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowReorderingInContextTracksReasons {
      get { return disallowReorderingInContextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_removing_from_next_tracks_reasons" field.</summary>
    public const int DisallowRemovingFromNextTracksReasonsFieldNumber = 19;
    private static readonly pb::FieldCodec<string> _repeated_disallowRemovingFromNextTracksReasons_codec
        = pb::FieldCodec.ForString(154);
    private readonly pbc::RepeatedField<string> disallowRemovingFromNextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowRemovingFromNextTracksReasons {
      get { return disallowRemovingFromNextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_removing_from_context_tracks_reasons" field.</summary>
    public const int DisallowRemovingFromContextTracksReasonsFieldNumber = 20;
    private static readonly pb::FieldCodec<string> _repeated_disallowRemovingFromContextTracksReasons_codec
        = pb::FieldCodec.ForString(162);
    private readonly pbc::RepeatedField<string> disallowRemovingFromContextTracksReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowRemovingFromContextTracksReasons {
      get { return disallowRemovingFromContextTracksReasons_; }
    }

    /// <summary>Field number for the "disallow_updating_context_reasons" field.</summary>
    public const int DisallowUpdatingContextReasonsFieldNumber = 21;
    private static readonly pb::FieldCodec<string> _repeated_disallowUpdatingContextReasons_codec
        = pb::FieldCodec.ForString(170);
    private readonly pbc::RepeatedField<string> disallowUpdatingContextReasons_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DisallowUpdatingContextReasons {
      get { return disallowUpdatingContextReasons_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Restrictions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Restrictions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!disallowPausingReasons_.Equals(other.disallowPausingReasons_)) return false;
      if(!disallowResumingReasons_.Equals(other.disallowResumingReasons_)) return false;
      if(!disallowSeekingReasons_.Equals(other.disallowSeekingReasons_)) return false;
      if(!disallowPeekingPrevReasons_.Equals(other.disallowPeekingPrevReasons_)) return false;
      if(!disallowPeekingNextReasons_.Equals(other.disallowPeekingNextReasons_)) return false;
      if(!disallowSkippingPrevReasons_.Equals(other.disallowSkippingPrevReasons_)) return false;
      if(!disallowSkippingNextReasons_.Equals(other.disallowSkippingNextReasons_)) return false;
      if(!disallowTogglingRepeatContextReasons_.Equals(other.disallowTogglingRepeatContextReasons_)) return false;
      if(!disallowTogglingRepeatTrackReasons_.Equals(other.disallowTogglingRepeatTrackReasons_)) return false;
      if(!disallowTogglingShuffleReasons_.Equals(other.disallowTogglingShuffleReasons_)) return false;
      if(!disallowSetQueueReasons_.Equals(other.disallowSetQueueReasons_)) return false;
      if(!disallowInterruptingPlaybackReasons_.Equals(other.disallowInterruptingPlaybackReasons_)) return false;
      if(!disallowTransferringPlaybackReasons_.Equals(other.disallowTransferringPlaybackReasons_)) return false;
      if(!disallowRemoteControlReasons_.Equals(other.disallowRemoteControlReasons_)) return false;
      if(!disallowInsertingIntoNextTracksReasons_.Equals(other.disallowInsertingIntoNextTracksReasons_)) return false;
      if(!disallowInsertingIntoContextTracksReasons_.Equals(other.disallowInsertingIntoContextTracksReasons_)) return false;
      if(!disallowReorderingInNextTracksReasons_.Equals(other.disallowReorderingInNextTracksReasons_)) return false;
      if(!disallowReorderingInContextTracksReasons_.Equals(other.disallowReorderingInContextTracksReasons_)) return false;
      if(!disallowRemovingFromNextTracksReasons_.Equals(other.disallowRemovingFromNextTracksReasons_)) return false;
      if(!disallowRemovingFromContextTracksReasons_.Equals(other.disallowRemovingFromContextTracksReasons_)) return false;
      if(!disallowUpdatingContextReasons_.Equals(other.disallowUpdatingContextReasons_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= disallowPausingReasons_.GetHashCode();
      hash ^= disallowResumingReasons_.GetHashCode();
      hash ^= disallowSeekingReasons_.GetHashCode();
      hash ^= disallowPeekingPrevReasons_.GetHashCode();
      hash ^= disallowPeekingNextReasons_.GetHashCode();
      hash ^= disallowSkippingPrevReasons_.GetHashCode();
      hash ^= disallowSkippingNextReasons_.GetHashCode();
      hash ^= disallowTogglingRepeatContextReasons_.GetHashCode();
      hash ^= disallowTogglingRepeatTrackReasons_.GetHashCode();
      hash ^= disallowTogglingShuffleReasons_.GetHashCode();
      hash ^= disallowSetQueueReasons_.GetHashCode();
      hash ^= disallowInterruptingPlaybackReasons_.GetHashCode();
      hash ^= disallowTransferringPlaybackReasons_.GetHashCode();
      hash ^= disallowRemoteControlReasons_.GetHashCode();
      hash ^= disallowInsertingIntoNextTracksReasons_.GetHashCode();
      hash ^= disallowInsertingIntoContextTracksReasons_.GetHashCode();
      hash ^= disallowReorderingInNextTracksReasons_.GetHashCode();
      hash ^= disallowReorderingInContextTracksReasons_.GetHashCode();
      hash ^= disallowRemovingFromNextTracksReasons_.GetHashCode();
      hash ^= disallowRemovingFromContextTracksReasons_.GetHashCode();
      hash ^= disallowUpdatingContextReasons_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      disallowPausingReasons_.WriteTo(output, _repeated_disallowPausingReasons_codec);
      disallowResumingReasons_.WriteTo(output, _repeated_disallowResumingReasons_codec);
      disallowSeekingReasons_.WriteTo(output, _repeated_disallowSeekingReasons_codec);
      disallowPeekingPrevReasons_.WriteTo(output, _repeated_disallowPeekingPrevReasons_codec);
      disallowPeekingNextReasons_.WriteTo(output, _repeated_disallowPeekingNextReasons_codec);
      disallowSkippingPrevReasons_.WriteTo(output, _repeated_disallowSkippingPrevReasons_codec);
      disallowSkippingNextReasons_.WriteTo(output, _repeated_disallowSkippingNextReasons_codec);
      disallowTogglingRepeatContextReasons_.WriteTo(output, _repeated_disallowTogglingRepeatContextReasons_codec);
      disallowTogglingRepeatTrackReasons_.WriteTo(output, _repeated_disallowTogglingRepeatTrackReasons_codec);
      disallowTogglingShuffleReasons_.WriteTo(output, _repeated_disallowTogglingShuffleReasons_codec);
      disallowSetQueueReasons_.WriteTo(output, _repeated_disallowSetQueueReasons_codec);
      disallowInterruptingPlaybackReasons_.WriteTo(output, _repeated_disallowInterruptingPlaybackReasons_codec);
      disallowTransferringPlaybackReasons_.WriteTo(output, _repeated_disallowTransferringPlaybackReasons_codec);
      disallowRemoteControlReasons_.WriteTo(output, _repeated_disallowRemoteControlReasons_codec);
      disallowInsertingIntoNextTracksReasons_.WriteTo(output, _repeated_disallowInsertingIntoNextTracksReasons_codec);
      disallowInsertingIntoContextTracksReasons_.WriteTo(output, _repeated_disallowInsertingIntoContextTracksReasons_codec);
      disallowReorderingInNextTracksReasons_.WriteTo(output, _repeated_disallowReorderingInNextTracksReasons_codec);
      disallowReorderingInContextTracksReasons_.WriteTo(output, _repeated_disallowReorderingInContextTracksReasons_codec);
      disallowRemovingFromNextTracksReasons_.WriteTo(output, _repeated_disallowRemovingFromNextTracksReasons_codec);
      disallowRemovingFromContextTracksReasons_.WriteTo(output, _repeated_disallowRemovingFromContextTracksReasons_codec);
      disallowUpdatingContextReasons_.WriteTo(output, _repeated_disallowUpdatingContextReasons_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      disallowPausingReasons_.WriteTo(ref output, _repeated_disallowPausingReasons_codec);
      disallowResumingReasons_.WriteTo(ref output, _repeated_disallowResumingReasons_codec);
      disallowSeekingReasons_.WriteTo(ref output, _repeated_disallowSeekingReasons_codec);
      disallowPeekingPrevReasons_.WriteTo(ref output, _repeated_disallowPeekingPrevReasons_codec);
      disallowPeekingNextReasons_.WriteTo(ref output, _repeated_disallowPeekingNextReasons_codec);
      disallowSkippingPrevReasons_.WriteTo(ref output, _repeated_disallowSkippingPrevReasons_codec);
      disallowSkippingNextReasons_.WriteTo(ref output, _repeated_disallowSkippingNextReasons_codec);
      disallowTogglingRepeatContextReasons_.WriteTo(ref output, _repeated_disallowTogglingRepeatContextReasons_codec);
      disallowTogglingRepeatTrackReasons_.WriteTo(ref output, _repeated_disallowTogglingRepeatTrackReasons_codec);
      disallowTogglingShuffleReasons_.WriteTo(ref output, _repeated_disallowTogglingShuffleReasons_codec);
      disallowSetQueueReasons_.WriteTo(ref output, _repeated_disallowSetQueueReasons_codec);
      disallowInterruptingPlaybackReasons_.WriteTo(ref output, _repeated_disallowInterruptingPlaybackReasons_codec);
      disallowTransferringPlaybackReasons_.WriteTo(ref output, _repeated_disallowTransferringPlaybackReasons_codec);
      disallowRemoteControlReasons_.WriteTo(ref output, _repeated_disallowRemoteControlReasons_codec);
      disallowInsertingIntoNextTracksReasons_.WriteTo(ref output, _repeated_disallowInsertingIntoNextTracksReasons_codec);
      disallowInsertingIntoContextTracksReasons_.WriteTo(ref output, _repeated_disallowInsertingIntoContextTracksReasons_codec);
      disallowReorderingInNextTracksReasons_.WriteTo(ref output, _repeated_disallowReorderingInNextTracksReasons_codec);
      disallowReorderingInContextTracksReasons_.WriteTo(ref output, _repeated_disallowReorderingInContextTracksReasons_codec);
      disallowRemovingFromNextTracksReasons_.WriteTo(ref output, _repeated_disallowRemovingFromNextTracksReasons_codec);
      disallowRemovingFromContextTracksReasons_.WriteTo(ref output, _repeated_disallowRemovingFromContextTracksReasons_codec);
      disallowUpdatingContextReasons_.WriteTo(ref output, _repeated_disallowUpdatingContextReasons_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += disallowPausingReasons_.CalculateSize(_repeated_disallowPausingReasons_codec);
      size += disallowResumingReasons_.CalculateSize(_repeated_disallowResumingReasons_codec);
      size += disallowSeekingReasons_.CalculateSize(_repeated_disallowSeekingReasons_codec);
      size += disallowPeekingPrevReasons_.CalculateSize(_repeated_disallowPeekingPrevReasons_codec);
      size += disallowPeekingNextReasons_.CalculateSize(_repeated_disallowPeekingNextReasons_codec);
      size += disallowSkippingPrevReasons_.CalculateSize(_repeated_disallowSkippingPrevReasons_codec);
      size += disallowSkippingNextReasons_.CalculateSize(_repeated_disallowSkippingNextReasons_codec);
      size += disallowTogglingRepeatContextReasons_.CalculateSize(_repeated_disallowTogglingRepeatContextReasons_codec);
      size += disallowTogglingRepeatTrackReasons_.CalculateSize(_repeated_disallowTogglingRepeatTrackReasons_codec);
      size += disallowTogglingShuffleReasons_.CalculateSize(_repeated_disallowTogglingShuffleReasons_codec);
      size += disallowSetQueueReasons_.CalculateSize(_repeated_disallowSetQueueReasons_codec);
      size += disallowInterruptingPlaybackReasons_.CalculateSize(_repeated_disallowInterruptingPlaybackReasons_codec);
      size += disallowTransferringPlaybackReasons_.CalculateSize(_repeated_disallowTransferringPlaybackReasons_codec);
      size += disallowRemoteControlReasons_.CalculateSize(_repeated_disallowRemoteControlReasons_codec);
      size += disallowInsertingIntoNextTracksReasons_.CalculateSize(_repeated_disallowInsertingIntoNextTracksReasons_codec);
      size += disallowInsertingIntoContextTracksReasons_.CalculateSize(_repeated_disallowInsertingIntoContextTracksReasons_codec);
      size += disallowReorderingInNextTracksReasons_.CalculateSize(_repeated_disallowReorderingInNextTracksReasons_codec);
      size += disallowReorderingInContextTracksReasons_.CalculateSize(_repeated_disallowReorderingInContextTracksReasons_codec);
      size += disallowRemovingFromNextTracksReasons_.CalculateSize(_repeated_disallowRemovingFromNextTracksReasons_codec);
      size += disallowRemovingFromContextTracksReasons_.CalculateSize(_repeated_disallowRemovingFromContextTracksReasons_codec);
      size += disallowUpdatingContextReasons_.CalculateSize(_repeated_disallowUpdatingContextReasons_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Restrictions other) {
      if (other == null) {
        return;
      }
      disallowPausingReasons_.Add(other.disallowPausingReasons_);
      disallowResumingReasons_.Add(other.disallowResumingReasons_);
      disallowSeekingReasons_.Add(other.disallowSeekingReasons_);
      disallowPeekingPrevReasons_.Add(other.disallowPeekingPrevReasons_);
      disallowPeekingNextReasons_.Add(other.disallowPeekingNextReasons_);
      disallowSkippingPrevReasons_.Add(other.disallowSkippingPrevReasons_);
      disallowSkippingNextReasons_.Add(other.disallowSkippingNextReasons_);
      disallowTogglingRepeatContextReasons_.Add(other.disallowTogglingRepeatContextReasons_);
      disallowTogglingRepeatTrackReasons_.Add(other.disallowTogglingRepeatTrackReasons_);
      disallowTogglingShuffleReasons_.Add(other.disallowTogglingShuffleReasons_);
      disallowSetQueueReasons_.Add(other.disallowSetQueueReasons_);
      disallowInterruptingPlaybackReasons_.Add(other.disallowInterruptingPlaybackReasons_);
      disallowTransferringPlaybackReasons_.Add(other.disallowTransferringPlaybackReasons_);
      disallowRemoteControlReasons_.Add(other.disallowRemoteControlReasons_);
      disallowInsertingIntoNextTracksReasons_.Add(other.disallowInsertingIntoNextTracksReasons_);
      disallowInsertingIntoContextTracksReasons_.Add(other.disallowInsertingIntoContextTracksReasons_);
      disallowReorderingInNextTracksReasons_.Add(other.disallowReorderingInNextTracksReasons_);
      disallowReorderingInContextTracksReasons_.Add(other.disallowReorderingInContextTracksReasons_);
      disallowRemovingFromNextTracksReasons_.Add(other.disallowRemovingFromNextTracksReasons_);
      disallowRemovingFromContextTracksReasons_.Add(other.disallowRemovingFromContextTracksReasons_);
      disallowUpdatingContextReasons_.Add(other.disallowUpdatingContextReasons_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            disallowPausingReasons_.AddEntriesFrom(input, _repeated_disallowPausingReasons_codec);
            break;
          }
          case 18: {
            disallowResumingReasons_.AddEntriesFrom(input, _repeated_disallowResumingReasons_codec);
            break;
          }
          case 26: {
            disallowSeekingReasons_.AddEntriesFrom(input, _repeated_disallowSeekingReasons_codec);
            break;
          }
          case 34: {
            disallowPeekingPrevReasons_.AddEntriesFrom(input, _repeated_disallowPeekingPrevReasons_codec);
            break;
          }
          case 42: {
            disallowPeekingNextReasons_.AddEntriesFrom(input, _repeated_disallowPeekingNextReasons_codec);
            break;
          }
          case 50: {
            disallowSkippingPrevReasons_.AddEntriesFrom(input, _repeated_disallowSkippingPrevReasons_codec);
            break;
          }
          case 58: {
            disallowSkippingNextReasons_.AddEntriesFrom(input, _repeated_disallowSkippingNextReasons_codec);
            break;
          }
          case 66: {
            disallowTogglingRepeatContextReasons_.AddEntriesFrom(input, _repeated_disallowTogglingRepeatContextReasons_codec);
            break;
          }
          case 74: {
            disallowTogglingRepeatTrackReasons_.AddEntriesFrom(input, _repeated_disallowTogglingRepeatTrackReasons_codec);
            break;
          }
          case 82: {
            disallowTogglingShuffleReasons_.AddEntriesFrom(input, _repeated_disallowTogglingShuffleReasons_codec);
            break;
          }
          case 90: {
            disallowSetQueueReasons_.AddEntriesFrom(input, _repeated_disallowSetQueueReasons_codec);
            break;
          }
          case 98: {
            disallowInterruptingPlaybackReasons_.AddEntriesFrom(input, _repeated_disallowInterruptingPlaybackReasons_codec);
            break;
          }
          case 106: {
            disallowTransferringPlaybackReasons_.AddEntriesFrom(input, _repeated_disallowTransferringPlaybackReasons_codec);
            break;
          }
          case 114: {
            disallowRemoteControlReasons_.AddEntriesFrom(input, _repeated_disallowRemoteControlReasons_codec);
            break;
          }
          case 122: {
            disallowInsertingIntoNextTracksReasons_.AddEntriesFrom(input, _repeated_disallowInsertingIntoNextTracksReasons_codec);
            break;
          }
          case 130: {
            disallowInsertingIntoContextTracksReasons_.AddEntriesFrom(input, _repeated_disallowInsertingIntoContextTracksReasons_codec);
            break;
          }
          case 138: {
            disallowReorderingInNextTracksReasons_.AddEntriesFrom(input, _repeated_disallowReorderingInNextTracksReasons_codec);
            break;
          }
          case 146: {
            disallowReorderingInContextTracksReasons_.AddEntriesFrom(input, _repeated_disallowReorderingInContextTracksReasons_codec);
            break;
          }
          case 154: {
            disallowRemovingFromNextTracksReasons_.AddEntriesFrom(input, _repeated_disallowRemovingFromNextTracksReasons_codec);
            break;
          }
          case 162: {
            disallowRemovingFromContextTracksReasons_.AddEntriesFrom(input, _repeated_disallowRemovingFromContextTracksReasons_codec);
            break;
          }
          case 170: {
            disallowUpdatingContextReasons_.AddEntriesFrom(input, _repeated_disallowUpdatingContextReasons_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            disallowPausingReasons_.AddEntriesFrom(ref input, _repeated_disallowPausingReasons_codec);
            break;
          }
          case 18: {
            disallowResumingReasons_.AddEntriesFrom(ref input, _repeated_disallowResumingReasons_codec);
            break;
          }
          case 26: {
            disallowSeekingReasons_.AddEntriesFrom(ref input, _repeated_disallowSeekingReasons_codec);
            break;
          }
          case 34: {
            disallowPeekingPrevReasons_.AddEntriesFrom(ref input, _repeated_disallowPeekingPrevReasons_codec);
            break;
          }
          case 42: {
            disallowPeekingNextReasons_.AddEntriesFrom(ref input, _repeated_disallowPeekingNextReasons_codec);
            break;
          }
          case 50: {
            disallowSkippingPrevReasons_.AddEntriesFrom(ref input, _repeated_disallowSkippingPrevReasons_codec);
            break;
          }
          case 58: {
            disallowSkippingNextReasons_.AddEntriesFrom(ref input, _repeated_disallowSkippingNextReasons_codec);
            break;
          }
          case 66: {
            disallowTogglingRepeatContextReasons_.AddEntriesFrom(ref input, _repeated_disallowTogglingRepeatContextReasons_codec);
            break;
          }
          case 74: {
            disallowTogglingRepeatTrackReasons_.AddEntriesFrom(ref input, _repeated_disallowTogglingRepeatTrackReasons_codec);
            break;
          }
          case 82: {
            disallowTogglingShuffleReasons_.AddEntriesFrom(ref input, _repeated_disallowTogglingShuffleReasons_codec);
            break;
          }
          case 90: {
            disallowSetQueueReasons_.AddEntriesFrom(ref input, _repeated_disallowSetQueueReasons_codec);
            break;
          }
          case 98: {
            disallowInterruptingPlaybackReasons_.AddEntriesFrom(ref input, _repeated_disallowInterruptingPlaybackReasons_codec);
            break;
          }
          case 106: {
            disallowTransferringPlaybackReasons_.AddEntriesFrom(ref input, _repeated_disallowTransferringPlaybackReasons_codec);
            break;
          }
          case 114: {
            disallowRemoteControlReasons_.AddEntriesFrom(ref input, _repeated_disallowRemoteControlReasons_codec);
            break;
          }
          case 122: {
            disallowInsertingIntoNextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowInsertingIntoNextTracksReasons_codec);
            break;
          }
          case 130: {
            disallowInsertingIntoContextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowInsertingIntoContextTracksReasons_codec);
            break;
          }
          case 138: {
            disallowReorderingInNextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowReorderingInNextTracksReasons_codec);
            break;
          }
          case 146: {
            disallowReorderingInContextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowReorderingInContextTracksReasons_codec);
            break;
          }
          case 154: {
            disallowRemovingFromNextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowRemovingFromNextTracksReasons_codec);
            break;
          }
          case 162: {
            disallowRemovingFromContextTracksReasons_.AddEntriesFrom(ref input, _repeated_disallowRemovingFromContextTracksReasons_codec);
            break;
          }
          case 170: {
            disallowUpdatingContextReasons_.AddEntriesFrom(ref input, _repeated_disallowUpdatingContextReasons_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
