// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: user_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spotify.Login5.V3 {

  /// <summary>Holder for reflection information generated from user_info.proto</summary>
  public static partial class UserInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for user_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg91c2VyX2luZm8ucHJvdG8SEXNwb3RpZnkubG9naW41LnYzIpcCCghVc2Vy",
            "SW5mbxIMCgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhYKDmVtYWlsX3Zl",
            "cmlmaWVkGAMgASgIEhEKCWJpcnRoZGF0ZRgEIAEoCRIyCgZnZW5kZXIYBSAB",
            "KA4yIi5zcG90aWZ5LmxvZ2luNS52My5Vc2VySW5mby5HZW5kZXISFAoMcGhv",
            "bmVfbnVtYmVyGAYgASgJEh0KFXBob25lX251bWJlcl92ZXJpZmllZBgHIAEo",
            "CBIgChhlbWFpbF9hbHJlYWR5X3JlZ2lzdGVyZWQYCCABKAgiOAoGR2VuZGVy",
            "EgsKB1VOS05PV04QABIICgRNQUxFEAESCgoGRkVNQUxFEAISCwoHTkVVVFJB",
            "TBADQhYKFGNvbS5zcG90aWZ5LmxvZ2luNXYzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Login5.V3.UserInfo), global::Spotify.Login5.V3.UserInfo.Parser, new[]{ "Name", "Email", "EmailVerified", "Birthdate", "Gender", "PhoneNumber", "PhoneNumberVerified", "EmailAlreadyRegistered" }, null, new[]{ typeof(global::Spotify.Login5.V3.UserInfo.Types.Gender) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserInfo : pb::IMessage<UserInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Login5.V3.UserInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo(UserInfo other) : this() {
      name_ = other.name_;
      email_ = other.email_;
      emailVerified_ = other.emailVerified_;
      birthdate_ = other.birthdate_;
      gender_ = other.gender_;
      phoneNumber_ = other.phoneNumber_;
      phoneNumberVerified_ = other.phoneNumberVerified_;
      emailAlreadyRegistered_ = other.emailAlreadyRegistered_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo Clone() {
      return new UserInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email_verified" field.</summary>
    public const int EmailVerifiedFieldNumber = 3;
    private bool emailVerified_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EmailVerified {
      get { return emailVerified_; }
      set {
        emailVerified_ = value;
      }
    }

    /// <summary>Field number for the "birthdate" field.</summary>
    public const int BirthdateFieldNumber = 4;
    private string birthdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Birthdate {
      get { return birthdate_; }
      set {
        birthdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 5;
    private global::Spotify.Login5.V3.UserInfo.Types.Gender gender_ = global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Login5.V3.UserInfo.Types.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "phone_number" field.</summary>
    public const int PhoneNumberFieldNumber = 6;
    private string phoneNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneNumber {
      get { return phoneNumber_; }
      set {
        phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number_verified" field.</summary>
    public const int PhoneNumberVerifiedFieldNumber = 7;
    private bool phoneNumberVerified_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool PhoneNumberVerified {
      get { return phoneNumberVerified_; }
      set {
        phoneNumberVerified_ = value;
      }
    }

    /// <summary>Field number for the "email_already_registered" field.</summary>
    public const int EmailAlreadyRegisteredFieldNumber = 8;
    private bool emailAlreadyRegistered_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EmailAlreadyRegistered {
      get { return emailAlreadyRegistered_; }
      set {
        emailAlreadyRegistered_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (EmailVerified != other.EmailVerified) return false;
      if (Birthdate != other.Birthdate) return false;
      if (Gender != other.Gender) return false;
      if (PhoneNumber != other.PhoneNumber) return false;
      if (PhoneNumberVerified != other.PhoneNumberVerified) return false;
      if (EmailAlreadyRegistered != other.EmailAlreadyRegistered) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (EmailVerified != false) hash ^= EmailVerified.GetHashCode();
      if (Birthdate.Length != 0) hash ^= Birthdate.GetHashCode();
      if (Gender != global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown) hash ^= Gender.GetHashCode();
      if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
      if (PhoneNumberVerified != false) hash ^= PhoneNumberVerified.GetHashCode();
      if (EmailAlreadyRegistered != false) hash ^= EmailAlreadyRegistered.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (EmailVerified != false) {
        output.WriteRawTag(24);
        output.WriteBool(EmailVerified);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Birthdate);
      }
      if (Gender != global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PhoneNumber);
      }
      if (PhoneNumberVerified != false) {
        output.WriteRawTag(56);
        output.WriteBool(PhoneNumberVerified);
      }
      if (EmailAlreadyRegistered != false) {
        output.WriteRawTag(64);
        output.WriteBool(EmailAlreadyRegistered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (EmailVerified != false) {
        output.WriteRawTag(24);
        output.WriteBool(EmailVerified);
      }
      if (Birthdate.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Birthdate);
      }
      if (Gender != global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PhoneNumber);
      }
      if (PhoneNumberVerified != false) {
        output.WriteRawTag(56);
        output.WriteBool(PhoneNumberVerified);
      }
      if (EmailAlreadyRegistered != false) {
        output.WriteRawTag(64);
        output.WriteBool(EmailAlreadyRegistered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (EmailVerified != false) {
        size += 1 + 1;
      }
      if (Birthdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Birthdate);
      }
      if (Gender != global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (PhoneNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
      }
      if (PhoneNumberVerified != false) {
        size += 1 + 1;
      }
      if (EmailAlreadyRegistered != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.EmailVerified != false) {
        EmailVerified = other.EmailVerified;
      }
      if (other.Birthdate.Length != 0) {
        Birthdate = other.Birthdate;
      }
      if (other.Gender != global::Spotify.Login5.V3.UserInfo.Types.Gender.Unknown) {
        Gender = other.Gender;
      }
      if (other.PhoneNumber.Length != 0) {
        PhoneNumber = other.PhoneNumber;
      }
      if (other.PhoneNumberVerified != false) {
        PhoneNumberVerified = other.PhoneNumberVerified;
      }
      if (other.EmailAlreadyRegistered != false) {
        EmailAlreadyRegistered = other.EmailAlreadyRegistered;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 24: {
            EmailVerified = input.ReadBool();
            break;
          }
          case 34: {
            Birthdate = input.ReadString();
            break;
          }
          case 40: {
            Gender = (global::Spotify.Login5.V3.UserInfo.Types.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 56: {
            PhoneNumberVerified = input.ReadBool();
            break;
          }
          case 64: {
            EmailAlreadyRegistered = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 24: {
            EmailVerified = input.ReadBool();
            break;
          }
          case 34: {
            Birthdate = input.ReadString();
            break;
          }
          case 40: {
            Gender = (global::Spotify.Login5.V3.UserInfo.Types.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 56: {
            PhoneNumberVerified = input.ReadBool();
            break;
          }
          case 64: {
            EmailAlreadyRegistered = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the UserInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Gender {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("MALE")] Male = 1,
        [pbr::OriginalName("FEMALE")] Female = 2,
        [pbr::OriginalName("NEUTRAL")] Neutral = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
